- name: Instalaci贸n de MariaDB y configuraci贸n
  hosts: mariadb
  become: yes
  become_method: sudo
  roles:
    - ins_mariadb

  - name: Instalaci贸n de Apache y configuraci贸n
  hosts: Apache
  become: yes
  become_method: sudo
  roles:
    - ins_apache

