- name: Instalación de MariaDB y configuración
  hosts: mariadb
  become: yes
  become_method: sudo
  roles:
    - ins_mariadb

  - name: Instalación de Apache y configuración
  hosts: Apache
  become: yes
  become_method: sudo
  roles:
    - ins_apache

- name: Instalación de PHP y Wordpress
  hosts: Apache
  become: yes
  become_method: sudo
  roles:
    - ins_php
