# Actualizar caché de los paquetes
- name: Actualizar caché de los repositorios
  apt:
    name: '*'
    state: latest
    update_cache: true
# Instalar MariaDB
- name: Instalación MariaDB
  apt:
          name:
            - mariadb-server
            - python3
            - python3-mysqldb
            - ufw
          state: latest
  when: ansible_facts.distribution == "Debian"

# Iniciar servicio MariaDB
- name: Iniciar servicio MariaDB
  service:
    name: mariadb
    enabled: true
    state: started
  when: ansible_facts.distribution == "Debian"
# Reiniciar el servicio de mariadb
- name: reiniciar servico MariaDB
  service:
    name: mariadb
    state: restarted
  tags: mariadb
  when: ansible_facts.distribution == "Debian"
      # Secure_installation y cambio de contraseña usuario root
- name: MySQL-secure_installation
  shell:
    echo -e "\nn\nY\nViewnext\nViewnext\nY\nn\nY\nY\n" | sudo mysql_secure_installation
  args:
    executable: /bin/bash
  tags: mariadb
  when: ansible_facts.distribution == "Debian"
# Creación de la base de datos de wordpress
- name: crear base de datos
  mysql_db:
    name: wordpress
    login_user: root
    login_password: Viewnext
    state: present
  tags: mariadb
  when: ansible_facts.distribution == "Debian"
# Usuario para la base de datos
- name: Crear usuario para base de datos de wordpress
  mysql_user:
    login_user: root
     login_password: Viewnext
    name: vagrant
    password: Viewnext
    priv: 'wordpress.]:ALL,GRANT'
    host: '%'
    state: present
  tags: mariadb
  when: ansible_facts.distribution == "Debian"
# Habilitar MariaDb en Firewall
- name: Habilitar servicio mysql en firewall
  ufw:
    state: enabled
  tags: mariadb
  when: ansible_facts.distribution == "Debian"
# Abrir puerto 3306 en firewall para conexión remota
- name: abrir pueto 3306
  ufw:
    rule: allow
    port: 3306
  tags: mariadb
  when: ansible_facts.distribution == "Debian"
# Habilitar puerto 22 firewall
- name: Habilitar puerto 22
  ufw:
    rule: allow
    port: 22
  when: ansible_facts.distribution == "Debian"
# Reiniciar servicio firewall
- name: Reiniciar la configuración del firewall
  ufw:
    state: reloaded
  tags: mariadb
  when: ansible_facts.distribution == "Debian"
